name: Build and Deploy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir build
          cp index.html build/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deploy do VPS zostanie wykonany w kolejnym kroku"
